# Generated by Django 5.0.3 on 2024-03-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_bathrooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
    ]
