version: '3.8'

services:
  web:
    build: ./djangobnb_backend
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./djangobnb_backend/ :/user/src/djangobnb_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    expose:
      - "15432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    #environment:
    #  - POSTGRES_USER:postgresuser
    #  - POSTGRES_PASSWORD:postgrespassword
    #  - POSTGRES_DB=djangobnb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
